spring.application.name=routeOptimizer

spring.datasource.url = jdbc:h2:file:./target/mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enables the H2 Console (localhost:8080/h2-console)
spring.h2.console.enabled=true
# Fix for H2 console access with Spring Security (if you add it later)
spring.h2.console.settings.web-allow-others=true

# Show SQL in logs (Great for learning JPA)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Set global logging level
logging.level.root=INFO

# Set specific level for your package
logging.level.com.app.RouteOptimizer=DEBUG

# Set level for Hibernate to see SQL parameters
#shows each parameter used in the SQL query which is generally replaced by placeholder '?' in query logs
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.security.user.name=myuser
spring.security.user.password=mypassword
